/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PaymentProcessorInterface extends Interface {
    getFunction(nameOrSignature: "owner" | "pay" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PaymentReceived"): EventFragment;

    encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pay', values: [string]): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace PaymentReceivedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish, orderId: string];
      export type OutputTuple = [from: string, amount: bigint, orderId: string];
      export interface OutputObject {from: string, amount: bigint, orderId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PaymentProcessor extends BaseContract {
    
    connect(runner?: ContractRunner | null): PaymentProcessor;
    waitForDeployment(): Promise<this>;

    interface: PaymentProcessorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pay: TypedContractMethod<
      [orderId: string, ],
      [void],
      'payable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pay'): TypedContractMethod<
      [orderId: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PaymentReceived'): TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;

    filters: {
      
      'PaymentReceived(address,uint256,string)': TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
      PaymentReceived: TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
    
    };
  }